#!/sbin/openrc-run
supervisor=supervise-daemon
respawn_delay=5
respawn_max=0
healthcheck_timer=30

name='Drone server'
command=/usr/bin/drone-server
command_user="drone:drone"

start_pre() {
    # the conf.d file might contain secrets!
    [ -f "/etc/conf.d/${RC_SVCNAME}" ] && checkpath --file --mode 0600 --owner root:root "/etc/conf.d/${RC_SVCNAME}"
    # make sure the default volume exists
    checkpath --directory --mode 0700 --owner drone:drone "/var/lib/${RC_SVCNAME}"
}
