kind: pipeline
type: exec
name: x86_64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - ./.scripts/drone.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      MC_HOST_master:
        from_secret: MC_HOST_master
      ABYSS_KEYBASE:
        from_secret: ABYSS_KEYBASE
      ABYSS_PRIVKEY:
        from_secret: ABYSS_PRIVKEY
      ABYSS_PUBKEY:
        from_secret: ABYSS_PUBKEY

---
kind: pipeline
type: exec
name: aarch64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    commands:
      - ./.scripts/drone.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      MC_HOST_master:
        from_secret: MC_HOST_master
      ABYSS_KEYBASE:
        from_secret: ABYSS_KEYBASE
      ABYSS_PRIVKEY:
        from_secret: ABYSS_PRIVKEY
      ABYSS_PUBKEY:
        from_secret: ABYSS_PUBKEY

---
kind: pipeline
type: exec
name: ppc64le

platform:
  os: linux
  arch: ppc64le

steps:
  - name: build
    commands:
      - ./.scripts/drone.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      MC_HOST_master:
        from_secret: MC_HOST_master
      ABYSS_KEYBASE:
        from_secret: ABYSS_KEYBASE
      ABYSS_PRIVKEY:
        from_secret: ABYSS_PRIVKEY
      ABYSS_PUBKEY:
        from_secret: ABYSS_PUBKEY

---
kind: pipeline
type: exec
name: mips64

platform:
  os: linux
  arch: mips64

steps:
  - name: build
    commands:
      - ./.scripts/drone.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      MC_HOST_master:
        from_secret: MC_HOST_master
      ABYSS_KEYBASE:
        from_secret: ABYSS_KEYBASE
      ABYSS_PRIVKEY:
        from_secret: ABYSS_PRIVKEY
      ABYSS_PUBKEY:
        from_secret: ABYSS_PUBKEY

---
kind: pipeline
type: exec
name: riscv64

platform:
  os: linux
  arch: riscv64

steps:
  - name: build
    commands:
      - ./.scripts/drone.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      MC_HOST_master:
        from_secret: MC_HOST_master
      ABYSS_KEYBASE:
        from_secret: ABYSS_KEYBASE
      ABYSS_PRIVKEY:
        from_secret: ABYSS_PRIVKEY
      ABYSS_PUBKEY:
        from_secret: ABYSS_PUBKEY
